[tool.poetry]
name = "image-gen"
version = "0.1.0"
description = ""
authors = ["tkk <t.kleylein@web.de>"]
readme = "README.md"
packages = [{include = "image_gen"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

